CREATE TABLE users (
	 FIRSTNAME VARCHAR (35)	NOT NULL,
	 LASTNAME VARCHAR (35) NOT NULL,
	 USERNAME VARCHAR (35) NOT NULL, 
	 EMAIL VARCHAR (320) NOT NULL, 
	 PASSWORD CHAR(40) NOT NULL, 
	 PRIV ENUM('admin', 'user', 'unverified') NOT NULL,
	 UNIQUE (EMAIL)
 );